{{- if .Values.schemaLoadJob.create -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.component }}-schema-loader
  labels:
    component: {{ .Values.component }}
 spec:
  template:
    spec:
      serviceAccountName: {{ .Values.component }}
      containers:
        - name: schema-loader
          image: 584455519448.dkr.ecr.us-east-1.amazonaws.com/schema-loader:2.0.3
          command: [ "bash","-x", "/run.sh" ]
          args: [ "{{ .Values.schemaLoadJob.type }}","{{ .Values.component }}" ]
          env:
            - name: env
              value: {{ .Values.env }}
      restartPolicy: Never
  backoffLimit: 1
{{- end }}

#1st line is condition to not create job for all components and mentioned in values.yaml
#to create job for remaining components need to mention in individual component helm prod.yaml
# assign env=prod in prod.yaml in component